Models/ErrorViewModel.cs
namespace Amardeep_LemonTechAssignment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Node.cs
using System.ComponentModel.DataAnnotations;

namespace Amardeep_LemonTechAssignment.Models
{
    public class Node
    {
        [Key]
        public int NodeId { get; set; }

        [Required]
        public string? NodeName { get; set; }

        public int? ParentNodeId { get; set; }

        [Required]
        public bool IsActive { get; set; }

        [Required]
        public string StartDate { get; set; }
    }
}

Models/Tree.cs
namespace Amardeep_LemonTechAssignment.Models
{
    public class Tree
    {
        public int id { get; set; }
        public string Name { get; set; }
        public List<Tree> Children { get; set; }
    }
}

Controllers/TreeController.cs
using Amardeep_LemonTechAssignment.Models;
using Amardeep_LemonTechAssignment.Repository;
using Microsoft.AspNetCore.Mvc;

namespace Amardeep_LemonTechAssignment.Controllers
{
    public class TreeController : Controller
    {
        private readonly ITree tree;

        public TreeController(ITree tree)
        {
            this.tree = tree;
        }

        [HttpGet]
        public  IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Node nodeValues)
        {
            if (ModelState.IsValid)
            {
                await tree.AddNode(nodeValues);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAllNodes()
        {
            List<Node> Nodeslist = await tree.GetAllNodes();
            return View(Nodeslist);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateNode(int id)
        {
            Node data = await tree.GetNodeById(id);
            TempData["CurrentNodeId"] = data.NodeId;
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateNode(Node nodeValue)
        {
            nodeValue.NodeId = (int)TempData["CurrentNodeId"];

            if (ModelState.IsValid)
            {
                await tree.UpdateNode(nodeValue);
                return RedirectToAction("GetAllNodes");
            }
            return View(nodeValue);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteNode(int id)
        {
            await tree.DeleteNode(id);
            return RedirectToAction("GetAllNodes");
        }

        [HttpGet]
        public async Task<IActionResult> GetParentsNodes()
        {
            List<Node> nodes = await tree.GetParentNodes();
            return View(nodes);
        }

        [HttpGet]
        public async Task<IActionResult> TreeView(int id)
        {

            List<Tree> result = await tree.BuildTree(id);
            return View(result);

        }
        
    }
}

Views/Shared/_ChildNodes.cshtml
@model List<Tree>

<ul>
   @* <li>*@
        @foreach (var node in Model)
        {

        <li>
            <span> @node.Name </span>
                @if (node.Children.Any())
                {
                <ul>
                        @*@Html.DisplayFor(m => node.Children)*@
                        @Html.Partial("_ChildNodes", node.Children)
                </ul>
                }
        </li>
        }
    @*</li>*@
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Amardeep_LemonTechAssignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Amardeep_LemonTechAssignment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Tree" asp-action="Index">Amardeep_LemonTechAssignment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
               
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Amardeep_LemonTechAssignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Tree/GetAllNodes.cshtml
@model IEnumerable<Node>

<table class="table table-hover caption-top">
    <thead>
        <tr>
            <th>Id</th>
            <th>Node Name</th>
            <th>Parent Node Id</th>
            <th>Is Active</th>
            <th>Start Date</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Node it in Model)
        {
            <tr>
                <td>@it.NodeId</td>
                <td>@it.NodeName</td>
                <td>@it.ParentNodeId</td>
                <td>@it.IsActive</td>
                <td>@it.StartDate</td>
                <td>
                    <a class="btn btn-outline-warning" asp-controller="Tree" asp-action="UpdateNode" asp-route-id="@it.NodeId">Update</a> &nbsp; &nbsp;
                    <a class="btn btn-outline-danger" asp-controller="Tree" asp-action="DeleteNode" asp-route-id="@it.NodeId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Tree/GetParentsNodes.cshtml
@model IEnumerable<Node>


<div class="row pt-2">
    <h2>All Parents Node</h2>
    <span>(Parents node are those nodes whose parentId is NULL)</span>
</div>
<ul class="list-group pt-3">
    @foreach (var it in Model)
    {
        <a asp-controller="Tree" asp-action="TreeView" asp-route-id="@it.NodeId">
          <div class="list-group pt-2">
                <button id="renderButton" type="button" class="list-group-item list-group-item-action">Parent NodeId : @it.NodeId</button>
          </div>
        </a>

    }
</ul>

Views/Tree/Index.cshtml
@model Node

@{
    Layout = "_Layout";
}
<div class="row pt-4">
    <div class="col-6">
        <h2 class="text-dark">Add Nodes</h2>
    </div>
    <div class="col-3">
        <a class="btn btn-outline-info" asp-controller="Tree" asp-action="GetAllNodes">All Nodes</a>
    </div>
    <div class="col-3">
        <a class="btn btn-outline-success" asp-controller="Tree" asp-action="GetParentsNodes">Generate Tree View</a>
    </div>
</div>

<div class="pt-5">
    <form method="post" asp-action="Index">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="row">
            <div class="col-3 form-group">
                <label asp-for="NodeName" class="control-label"></label>
            </div>
            <div class="col-9 form-group">
                <input asp-for="NodeName" class="form-control" />
                <span asp-validation-for="NodeName" class="text-danger"></span>
            </div>
        </div>
        <div class="row pt-3">
            <div class="col-3 form-group">
                <label asp-for="ParentNodeId" class="control-label"></label>
            </div>
            <div class="col-9 form-group">
                <input asp-for="ParentNodeId" class="form-control" />
            </div>
        </div>
        <div class="row pt-3">
            <div class="col-6">
                <div class="row">
                    <div class="col-3  form-group">
                        <label asp-for="IsActive" class="form-check-label"></label>
                    </div>
                    <div class="col-3  form-group">
                        <input asp-for="IsActive" class="form-check-input" type="checkbox" />
                        <span asp-validation-for="IsActive" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="row">
                    <div class="col-3  form-group">
                        <label asp-for="StartDate" class="control-label"></label>
                    </div>
                    <div class="col-3  form-group">
                        <input asp-for="StartDate" class="form-control" type="date" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row pt-4">
            <div class="form-group">
                <input type="submit" value="Add Node" class="btn btn-success" />
            </div>
        </div>
    </form>
</div>

Views/Tree/TreeView.cshtml
@model List<Tree>

<div class="row pt-3 pb-3">
    <h2> Tree structure </h2>
    <span>(If parent node does not have any childern than NO Tree will be generated)</span>
</div>

<ul>
    @foreach (var node in Model)
    {
        <li>
            <span> @node.Name</span>
            @if (node.Children.Any())
            {
                 @Html.Partial("_ChildNodes", node.Children)  
            }
        </li>
    }
</ul>

Views/Tree/UpdateNode.cshtml
@model Node

<div class="pt-5">
    <form method="post" asp-action="Index">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="row">
            <div class="col-3 form-group">
                <label asp-for="NodeName" class="control-label"></label>
            </div>
            <div class="col-9 form-group">
                <input asp-for="NodeName" class="form-control" />
                <span asp-validation-for="NodeName" class="text-danger"></span>
            </div>
        </div>
        <div class="row pt-3">
            <div class="col-3 form-group">
                <label asp-for="ParentNodeId" class="control-label"></label>
            </div>
            <div class="col-9 form-group">
                <input asp-for="ParentNodeId" class="form-control" />
            </div>
        </div>
        <div class="row pt-3">
            <div class="col-6">
                <div class="row">
                    <div class="col-3  form-group">
                        <label asp-for="IsActive" class="form-check-label"></label>
                    </div>
                    <div class="col-3  form-group">
                        <input asp-for="IsActive" class="form-check-input" type="checkbox" />
                        <span asp-validation-for="IsActive" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="row">
                    <div class="col-3  form-group">
                        <label asp-for="StartDate" class="control-label"></label>
                    </div>
                    <div class="col-3  form-group">
                        <input asp-for="StartDate" class="form-control" type="date" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row pt-4">
            <div class="form-group">
                <input type="submit" value="Add Node" class="btn btn-success" />
            </div>
        </div>
    </form>
</div>